import { defineConfig } from "tsup";
import { copyFileSync, mkdirSync } from "fs";
import { join } from "path";

export default defineConfig({
  entry: ["./src/index.ts"],
  format: ["esm", "cjs"],
  dts: true,
  clean: true,
  minify: true,
  sourcemap: true,
  // `treeshake` is intentionally left off (defaults to `false`). Enabling it
  // routes the bundle through a second, Rollup-based treeshake pass on top of
  // esbuild's own treeshaking — and that Rollup pass is the sole source of the
  // "using named and default exports together" (MIXED_EXPORTS) warning on the
  // CJS entry, because this package deliberately exposes both a default export
  // (`Pixel`) and named exports (`Pixel`, `Skeleton`, `buildPixelUrl`,
  // `buildPixelSources`, `getMimeType`).
  //
  // The warning cannot be scoped away in tsup 8.5.1: the internal treeshake
  // pass hard-codes `onwarn: silent ? noop : undefined`, so the only built-in
  // lever is the global `silent` flag, which would also hide genuine warnings.
  // Fixing it via `output.exports: "named"` is not an option either — that
  // would force every default-import consumer onto `.default`, a breaking
  // change for what is meant to be a purely additive dual export.
  //
  // esbuild already tree-shakes (and we still `minify`), so dropping the
  // redundant Rollup pass leaves the emitted bundle functionally equivalent
  // for this dependency-light component (the CJS interop scaffold is now
  // generated by esbuild rather than Rollup, so it is equivalent in behavior
  // rather than byte-identical in text) while producing a genuinely
  // warning-free build. `package.json#exports` continues to resolve ESM/CJS
  // consumers to the correct condition, and both `require(pkg).default` and
  // `require(pkg).Pixel` still resolve to the same component reference.
  target: "es2022",
  platform: "neutral",
  splitting: false,
  external: ["react"],
  shims: true,
  loader: {
    ".avif": "dataurl",
    ".webp": "dataurl",
    ".jpg": "dataurl",
    ".png": "dataurl",
  },
  async onSuccess() {
    // Create assets directory if it doesn't exist
    mkdirSync("dist/assets", { recursive: true });

    // Copy all image files to dist/assets
    const imageFiles = [
      "src/assets/noimage.avif",
      "src/assets/noimage.webp",
      "src/assets/noimage.jpg",
      "src/assets/noavatar.avif",
      "src/assets/noavatar.webp",
      "src/assets/noavatar.png",
    ];

    imageFiles.forEach((file) => {
      const fileName = file.split("/").pop();
      // Add a null check to ensure fileName is not undefined
      if (fileName) {
        copyFileSync(file, join("dist/assets", fileName));
      }
    });
  },
});
